services:
  - type: web
    name: taustars-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python TauStarsRef.py
    region: frankfurt
    pythonVersion: 3.10.12
